### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by Code-Slave** [Misterio77/disconic#1] opened 2022-02-04 02:06 UTC
Hi. trying to set this up. any quick doc on usage?

**Comment by Misterio77** [comment] 2022-02-04 02:14
Hey! It's still a bit WIP (queues currently are a little buggy, and i plan on implementing a command for queuing entire albums or random songs from a specific artist), but should work!

All you need to do is build (using `cargo build`), and run with the following env vars set (you can add them to a `.env` if you prefer):
- `SUBSONIC_URL` (base URL of your subsonic server, including `http` or `https`)
- `SUBSONIC_USER`
- `SUBSONIC_PASSWORD`
- `DISCORD_TOKEN` (get yours at https://discord.com/developers/applications)

**Comment by Code-Slave** [comment] 2022-02-04 02:32
Thanks. I just want to select and play a playlist for my buddies when we play games. what works?

**Comment by Misterio77** [comment] 2022-02-04 02:35
Currently, you can queue named (using `~play`) or random (using `~random`) songs, and manage the queue (`~queue`, `~remove`, `~nowplaying`). They do play nicely as expected.

I'm not sure why (trying to fix this atm), when 2+ songs are queued they tend to skip mid song, which is quite bad. Possibly something related to ffmpeg, I've been trying to stream the bits directly now.

When this is fixed, I plan to implement queueing entire albums, multiple songs from an artist, and playlists. These are quite easy to do.

**Comment by Misterio77** [comment] 2022-02-04 02:36
I can give you a ping when I get this fixed and playlists implemented, if you want :)

**Comment by Code-Slave** [comment] 2022-02-04 02:37
sure. i assume you have to have it join a voice channel?

**Comment by Misterio77** [comment] 2022-02-04 02:39
Yup, that's right. Just invite your bot, then get into a channel and run `~join`.

**Comment by Code-Slave** [comment] 2022-02-04 02:39
oof. Im not a rust dev at all. cargo build. just did a git clone and cargo build. env is as above


error: failed to get `sunk` as a dependency of package `disconic v0.2.1 (/data/projects/disconic)`

Caused by:
  failed to load source for dependency `sunk`

Caused by:
  Unable to update https://github.com/Misterio77/sunk#a9394882

Caused by:
  failed to parse manifest at `/home/smayes/.cargo/git/checkouts/sunk-af4538eb5f7fbc55/a939488/Cargo.toml`

Caused by:
  feature `edition2021` is required

  consider adding `cargo-features = ["edition2021"]` to the manifest

**Comment by Misterio77** [comment] 2022-02-04 02:40
Oops, maybe you have an outdated rustc version? What's your distro?

I can also compile it and make a release, just gimme a sec.

**Comment by Code-Slave** [comment] 2022-02-04 02:40
ubuntu 21.10

rustc is already the newest version (1.53.0+dfsg1+llvm-4ubuntu1~21.10.1).

appreciate the help btw

**Comment by Misterio77** [comment] 2022-02-04 02:48
It seems rust 2021 requires rustc >= 1.56.0 (quite the bleeding edge I'd say).

Here's a release i just made with the compiled binary: https://github.com/Misterio77/disconic/releases/download/0.2.1/disconic-0.2.1-x86_64-unknown-linux-gnu.tar.gz

Just untar it, run the `disconic` binary (make sure your `.env` is in the same dir), and you should be good to go!

And it's not a problem at all to help out :)

**Comment by Code-Slave** [comment] 2022-02-04 02:50
thanks

btw updated rust and build failed on system alsa libs. ill mess with it some

**Comment by Misterio77** [comment] 2022-02-04 02:54
Hmm yeah there's a few dependencies i forgot about lol.
It's pretty much: autoconf, automake (you probably have these two), alsa-lib, libopus, and ffmpeg.

I think `apt install alsa-lib libopus-dev ffmpeg` should get you going.

**Comment by Code-Slave** [comment] 2022-02-04 03:46
got it to compile

joined voice channel.

~play songname

song: Reqwest(reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) })

I should say I am using navidrome as my server. maybe thats a problem as it may not have the api calls completely

**Comment by Misterio77** [comment] 2022-02-04 05:00
Hmm that's weird. Navidrome should work nicely (it's what i use actually).

**Comment by Code-Slave** [comment] 2022-02-04 13:28
anything that tries to play a song does that. do you need quotes or something for song name?
also in env file
SUBSONIC_URL=http://192.168.1.198:4000/

is that right or should i just use ip:port

?

**Comment by Code-Slave** [comment] 2022-02-04 15:15
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src/discord/mod.rs:61:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
song: Reqwest(reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) })

want me to run backtrace?

**Comment by Misterio77** [comment] 2022-02-04 15:20
Your URL seems fine (i use `https://music.misterio.me`), and no need to quote the songs indeed.

Maybe the URL is somehow non canonical (maybe remove the trailling slash?), can you try running `curl http://192.168.1.198:400/` to see if you get somehow redirected?

**Comment by Code-Slave** [comment] 2022-02-04 16:16
/app/ Found


so curl works

**Comment by Code-Slave** [comment] 2022-02-04 16:21
song: Reqwest(reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) })
random: Reqwest(reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) })

**Comment by Misterio77** [comment] 2022-02-04 17:02
It seems the API response somehow isn't as the lib expects. Can you try doing a subsonic API request manually?

**Comment by Code-Slave** [comment] 2022-02-04 19:52
Have an example request?

**Comment by Code-Slave** [comment] 2022-02-04 20:38
i did a ping and a getplaylist. both work fine

`<subsonic-response xmlns="http://subsonic.org/restapi" status="ok" version="1.16.1" type="navidrome" serverVersion="0.47.0 (8c7d95c1)"></subsonic-response>`

**Comment by Misterio77** [comment] 2022-02-04 21:46
Could you show which URL you used to do the request (of course, redacting the private stuff as needed)?

**Comment by Code-Slave** [comment] 2022-02-05 01:33
http://192.168.1.198:4000/rest/search2?query=Vali&u=user&p=pass&v=1.16.1&c=myapp

that runs fine

**Comment by Code-Slave** [comment] 2022-02-06 13:07
any idea?

**Comment by Misterio77** [comment] 2022-02-10 02:38
Hey, sorry for the delay, busy week.

I'm out of ideas, I'm afraid ://

**Comment by Misterio77** [comment] 2023-06-11 23:32
Hi @Code-Slave! Not sure if you're still interested in this, but just in case:

I've since refactored this, fixed the queue issue that prevented me from actually using it, and migrated to slash commands. There's documentation on the README to help you run it :)

Let me know if there's anything I can do to help!

**Comment by Misterio77** [comment] 2023-06-11 23:35
Oh and the issue I believe you were facing was fixed. The problem is that navidrome uses non-numeric IDs, while `sunk` only supported numeric ones.

**Comment by Code-Slave** [comment] 2023-06-22 13:05
Great. Ill give it a whirl this weekend. Thanks for the update

**Comment by Misterio77** [comment] 2023-12-04 20:16
I've since add docs, so will close this issue. Feel free to reopen if you need any help!

**Closed as completed by Misterio77** 2023-12-04 20:16 UTC
Labels: documentation
